apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: conecta-letsencrypt
  namespace: conecta-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: edson@novadata.com.br  # Coloque o seu email
    privateKeySecretRef:
      name: conecta-letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
