apiVersion: v1
kind: Service
metadata:
  name: conecta-service
  namespace: conecta-dev
spec:
  selector:
    app: conecta
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
