kubectl create secret docker-registry dockerhub-secret \
  --docker-username=adriano.pimentel@novadata.com.br \
  --docker-password=amelhorsenhadomundo \
  --docker-email=adriano.pimentel@novadata.com.br \
  --namespace=conecta-prod
